class MockLLM:
    provider = "mock"

    def __init__(self, model: str):
        self.model = model

    def invoke(self, messages: list[dict[str, str]]) -> str:
        user_messages = [m["content"] for m in messages if m.get("role") == "user"]
        latest = user_messages[-1] if user_messages else ""
        return (
            f"Mock response for: {latest}\n\n"
            "This response was generated by the free local test backend. "
            "The LangGraph state and checkpointing flow are real."
        )
